#!C:\Perl64\bin\perl
##!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }
$ENV{MOJO_DAEMON_DEBUG}=1;
#$ENV{MOJO_LISTEN}=[ qw (http://127.0.0.1:3000 https://127.0.0.1:4000) ];
#print "$FindBin::Bin/../lib";
# Start command line interface for application
require Mojolicious::Commands;

Mojolicious::Commands->start_app('TechUtsav');
